apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virulaservice.name }}
  namespace: {{ .Values.department }}
spec:
  gateways:
  - services/services-gateway
  - services/customer-admin-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: {{ .Values.virulaservice.prefix }}
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ .Values.service.name }}
        port:
          number: {{ .Values.service.port }}