#
# MIT License
#
# (C) Copyright 2025 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
---
# This task performs CEPH zoning whose objective is to make sure data gets replicated at rack level, so there would not be data loss incase of a rack failure
- name: Check for existence of rack placement file generated from the play mgmt_nodes_placement_discovery
  stat:
    path: "/tmp/rack_placement.json"
  register: placement_file


- name: Perform CEPH zoning
  script: ceph_zoning.py /tmp/rack_placement.json
  args:
    executable: python
  when: placement_file.stat.exists
  register: ceph_zoning_output
  delegate_to: "{{ play_hosts | first }}"
  changed_when: ceph_zoning_output.rc == 0


- name: Print output from the Python script
  debug:
    msg: "{{ ceph_zoning_output.stdout }}"  
