name: cray-rrs-api
department: rack-resiliency
replicaCount: 1
image:
  repository: library/base
  tag: "1.1"
  pullPolicy: Never
service:
  name: cray-rrs-api
  type: ClusterIP
  port: 80
  targetPort: 80
volumes:
  sshConfigPath: /etc/ssh
  sshHpPath: /root/.ssh
  cephConfigName: ceph-admin-config
  criticalSvcConfigName: rrs-map
auth:
  serviceAccount: cray-rrs-reader
  clusterRole: cray-rrs-role
  clusterRoleBinding: cray-rrs-rolebinding
virtualservice:
  name: cray-rrs-vs
  prefix: /apis/rrs
  
