apiVersion: v1
kind: ConfigMap
metadata:
  name: rrs-mon-dynamic
  namespace: rack-resiliency
  labels:
    app.kubernetes.io/managed-by: Helm
    type: rr-services 
data:
  dynamic-data.yaml: |-
    timestamps:
      start_timestamp_rms: "" 
      start_timestamp_api: ""
      last_update_timestamp: ""
      start_timestamp_k8s_monitoring: ""
      end_timestamp_k8s_monitoring: ""
      start_timestamp_ceph_monitoring: ""
      end_timestamp_ceph_monitoring: ""
    state:
      k8s_monitoring: ""
      ceph_monitoring: ""
      rms_state: ""
    last_updated_by:
      name: ""
    zone:
      k8s_zones_with_nodes: ""
      ceph_zones_with_nodes: ""
  critical-service-config.json: |-
    {
      "critical-services": {
        “coredns”: {
          “namespace”: “kube-system”,
          “type”: "Deployment”
         },
        “sealed-secrets”: {
          “namespace”: “kube-system”,
          “type”: "Deployment”
         },
        “cray-ceps-csi-cephfs-provisioner”: {
          “namespace”: “ceph-cephfs”,
          “type”: "Deployment”
         },
        “cray-ceph-csi-rbd-provisioner”: {
          “namespace”: “ceph-rbd”,
          “type”: "Deployment”
         },
        “cray-activemq-artemis-operator-controller-manager”: {
          “namespace”: “dvs”,
          “type”: "Deployment”
         },
        “cray-dvs-mqtt-ss”: {
          “namespace”: “dvs”,
          “type”: "Statefulset”
         },
        “cray-hmnfd-bitnami-etcd”: {
          “namespace”: “services”,
          “type”: "Statefulset”
         },
        “cray-hmnfd”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        “cray-hbtd”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        “cray-hbtd”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        “Cray-hbtd-bitnami-etcd”: {
          “namespace”: “services”,
          “type”: "Statefulset”
         },
        “hpe-slingshot-jackaloped”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        “hpe-slingshot-ogopogod”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        “slingshot-fabric-manager”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        “hpe-slingshot-vnid”: {
          “namespace”: “services”,
          “type”: "Statefulset”
         },
        “cray-console-node”: {
          “namespace”: “services”,
          “type”: "Statefulset”
         },
        “cray-console-data-postgres”: {
          “namespace”: “services”,
          “type”: "Statefulset”
         },
        “cray-dns-powerdns”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        “cray-powerdns-manager”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        “cray-dns-powerdns-manager”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        “cray-dhcp-kea”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        “cray-dhcp-kea-postgres”: {
          “namespace”: “services”,
          “type”: "Statefulset”
         },
        “cray-sls”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        “cray-sls-postgres”: {
          “namespace”: “services”,
          “type”: "Statefulset”
         },
        “cray-keycloak”: {
          “namespace”: “services”,
          “type”: "Statefulset”
         },
        “keycloak-postgres”: {
          “namespace”: “services”,
          “type”: "Statefulset”
         },
        “slurm-operator”: {
          “namespace”: “slurm-operator”,
          “type”: "Deployment”
         },
        “slurmctld”: {
          pace”: “user”,
          “type”: "Deployment”
         },
        “slurmctld-backup”: {
          “namespace”: “user”,
          “type”: "Deployment”
         },
        “slurmdbd”: {
          “namespace”: “user”,
          “type”: "Deployment”
         },
        “slurmdbd-backup”: {
          “namespace”: “user”,
          “type”: "Deployment”
         },
        “slurmdbd”: {
          “namespace”: “user”,
          “type”: "Deployment”
         },
        “slurmdbd-backup”: {
          “namespace”: “user”,
          “type”: "Deployment”
         },
        “slurmdb-haproxy”: {
          “namespace”: “user”,
          “type”: "Statefulset”
         },
        “slurmdb-pxc”: {
          “namespace”: “user”,
          “type”: "Statefulset”
         },
        “pbs”: {
          “namespace”: “user”,
          “type”: "Deployment”
         },
        “pbs-comm”: {
          ce”: “user”,
          “type”: "Deployment”
         },
        “cray-spire-postgres”: {
          “namespace”: “spire”,
          “type”: "Statefulset”
         },
        “spire-postgres”: {
          “namespace”: “spire”,
          “type”: "Statefulset”
         },
        “cray-spire-server”: {
          “namespace”: “spire”,
          “type”: "Statefulset”
         },
        “spire-server”: {
          “namespace”: “spire”,
          “type”: "Statefulset”
         },
        “cilium-operator”: {
          “namespace”: “kube-system”,
          “type”: "Deployment”
         },
        “cray-smd”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        “cray-smd-postgres”: {
          “namespace”: “services”,
          “type”: "Statefulset”
         },
        “cray-bss”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        “cray-bss-bitnami-etcd”: {
          “namespace”: “services”,
          “type”: "Statefulset”
         },
        “cray-tfpd”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        “cray-ipxe-aarch64”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        “cray-ipxe-x86-64”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        “cray-vault-configurer”: {
          “namespace”: “vault”,
          “type”: "Deployment”
         },
        “cray-vault-operator”: {
          “namespace”: “vault”,
          “type”: "Deployment”
         },
        “cray-vault”: {
          “namespace”: “vault”,
          “type”: "Statefulset”
         },
        “cray-sts”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        “cray-ara”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        “cray-hwsync-agent”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        “cray-trust”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        “cray-cfs-api”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        “cray-cfs-api-db”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        “cray-cfs-batcher”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        “cray-cfs-operator”: {
          “namespace”: “services”,
          “type”: "Statefulset”
         },
        “cray-bos”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        “cray-bos-db”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        "nexus": {
          "namespace": "nexus",
          "type": "Deployment”
         },
        “kyverno-admission-controller”: {
          “namespace”: “kyverno”,
          “type”: "Deployment”
         },
        “kyverno-background-controller”: {
          “namespace”: “kyverno”,
          “type”: "Deployment”
         },
        “kyverno-cleanup-controller”: {
          “namespace”: “kyverno”,
          “type”: "Deployment”
         },
        “kyverno-reports-controller”: {
          “namespace”: “kyverno”,
          “type”: "Deployment”
         },
        “cray-certmanager-cert-manager”: {
          “namespace”: “cert-manager”,
          “type”: "Deployment”
         },
        “cray-certmanager-cert-manager-cainjector”: {
          “namespace”: “cert-manager”,
          “type”: "Deployment”
         },
        “cray-certmanager-cert-manager-webhook”: {
          “namespace”: “cert-manager”,
          m“type”: "Deployment”
         },
        “istio-operator”: {
          “namespace”: “istio-operator”,
          “type”: "Deployment”
         },
        “istio-ingressgateway”: {
          “namespace”: “istio-system”,
          “type”: "Deployment”
         },
        “istio-ingressgateway-customer-admin”: {
          “namespace”: “istio-system”,
          “type”: "Deployment”
         },
        “istio-ingressgateway-customer-user”: {
          “namespace”: “istio-system”,
          “type”: "Deployment”
         },
        “istio-ingressgateway-hmn”: {
          “namespace”: “istio-system”,
          “type”: "Deployment”
         },
        “istiod”: {
          “namespace”: “istio-system”,
          “type”: "Deployment”
         },
        “kiali”: {
          “namespace”: “istio-system”,
          “type”: "Deployment”
         },
        “gitea-vcs”: {
          “namespace”: “services”,
          “type”: "Deployment”
         },
        “gitea-vcs-postgres”: {
          “namespace”: “services”,
          “type”: “Statefulset”
         },
        “cray-bss”: {
          “namespace”: “services”,
          “type”: “Deployment”
         },
        “cray-bss-bitnami-etcd”: {
          “namespace”: “services”,
          “type”: “Statefulset”
         },
        “cray-sls”: {
          “namespace”: “services”,
          “type”: “Deployment”
         },
        “cray-sls-postgres”: {
          “namespace”: “services”,
          “type”: “Statefulset”
         },
        “cray-power-control”: {
          “namespace”: “services”,
          “type”: “Deployment”
         },
        “cray-power-control-bitnami-etcd”: {
          “namespace”: “services”,
          “type”: “Statefulset”
         },
        “cray-capmc”: {
          “namespace”: “services”,
          “type”: “Deployment”
         },
        “cray-tftp”: {
          “namespace”: “services”,
          “type”: “Deployment”
         },
        “gitea-vcs”: {
          “namespace”: “services”,
          “type”: “Deployment”
         },
        “gitea-vcs-postgres”: {
          “namespace”: “services”,
          “type”: “Statefulset”
         },
        “kube-apiserver”: {
          “namespace”: “kube-system”,
          “type”: “static pod”
         },
        “kube-controller-manager”: {
          “namespace”: “kube-system”,
          “type”: “static pod”
         },
        “kube-scheduler”: {
          “namespace”: “kube-system”,
          “type”: “static pod”
         },
      }
    }
