apiVersion: v1
kind: ConfigMap
metadata:
  name: rrs-mon-dynamic
  namespace: rack-resiliency
  labels:
    app.kubernetes.io/managed-by: Helm
    type: rr-services 
data:
  dynamic-data.yaml: |-
    timestamps:
      start_timestamp_rms: "" 
      start_timestamp_api: ""
      last_update_timestamp: ""
      start_timestamp_k8s_monitoring: ""
      end_timestamp_k8s_monitoring: ""
      start_timestamp_ceph_monitoring: ""
      end_timestamp_ceph_monitoring: ""
    state:
      k8s_monitoring: ""
      ceph_monitoring: ""
      rms_state: ""
    last_updated_by:
      name: ""
    rrs:
      zone: ""
      node: ""
    zone:
      # k8s_zones is an array of zones which is again array of nodes
      # k8s_zones:
      #     - name: "x3000"
      #        management_master:
      #            - "ncn-m001"
      #        management_worker:
      #            - "ncn-w001"
      #            - "ncn-w002"
      #     - name: "x3001"
      #        management_master:
      #            - "ncn-m002"
      #        management_worker:
      #            - "ncn-w003"
      #            - "ncn-w004"
      k8s_zones: ""
      # ceph_zones is an array of zones which is again an array of nodes which is again an array of OSD's
      # ceph_zones:
      #     - name: "x3000"
      #        management_storage:
      #            - name: "ncn-s001"
      #               - osd.1
      #               - osd.2
      #     - name: "x3001"
      #        management_storage:
      #            - name: "ncn-s002"
      #               - osd.3
      #               - osd.4
      #            - name: "ncn-s003"
      #               - osd.5
      #               - osd.6
      ceph_zones: ""
  critical-service-config.json: |-
    {
      "critical-services": {
        "coredns": {
          "namespace": "kube-system",
          "type": "Deployment"
          # status can have value as 
          # - Configured/Unconfigured 
          # - Recovering
          # - Recovered
          # - Configured (from recovered after 2 cycles of observation)
          "status": ""
          "balanced": ""
        },
        "sealed-secrets": {
          "namespace": "kube-system",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-ceph-csi-cephfs-provisioner": {
          "namespace": "ceph-cephfs",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-ceph-csi-rbd-provisioner": {
          "namespace": "ceph-rbd",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-activemq-artemis-operator-controller-manager": {
          "namespace": "dvs",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-dvs-mqtt-ss": {
          "namespace": "dvs",
          "type": "StatefulSet"
          "status": ""
          "balanced": ""
        },
        "cray-hmnfd-bitnami-etcd": {
          "namespace": "services",
          "type": "StatefulSet"
          "status": ""
          "balanced": ""
        },
        "cray-hmnfd": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-hbtd": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-hbtd-bitnami-etcd": {
          "namespace": "services",
          "type": "StatefulSet"
          "status": ""
          "balanced": ""
        },
        "hpe-slingshot-jackaloped": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "hpe-slingshot-ogopogod": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "slingshot-fabric-manager": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "hpe-slingshot-vnid": {
          "namespace": "services",
          "type": "StatefulSet"
          "status": ""
          "balanced": ""
        },
        "cray-console-node": {
          "namespace": "services",
          "type": "StatefulSet"
          "status": ""
          "balanced": ""
        },
        "cray-console-data-postgres": {
          "namespace": "services",
          "type": "StatefulSet"
          "status": ""
          "balanced": ""
        },
        "cray-dns-powerdns": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-powerdns-manager": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-dns-powerdns-manager": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-dhcp-kea": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-dhcp-kea-postgres": {
          "namespace": "services",
          "type": "StatefulSet"
          "status": ""
          "balanced": ""
        },
        "cray-sls": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-sls-postgres": {
          "namespace": "services",
          "type": "StatefulSet"
          "status": ""
          "balanced": ""
        },
        "cray-keycloak": {
          "namespace": "services",
          "type": "StatefulSet"
          "status": ""
          "balanced": ""
        },
        "keycloak-postgres": {
          "namespace": "services",
          "type": "StatefulSet"
          "status": ""
          "balanced": ""
        },
        "slurm-operator": {
          "namespace": "slurm-operator",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "slurmctld": {
          "namespace": "user",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "slurmctld-backup": {
          "namespace": "user",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "slurmdbd": {
          "namespace": "user",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "slurmdbd-backup": {
          "namespace": "user",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "slurmdb-haproxy": {
          "namespace": "user",
          "type": "StatefulSet"
          "status": ""
          "balanced": ""
        },
        "slurmdb-pxc": {
          "namespace": "user",
          "type": "StatefulSet"
          "status": ""
          "balanced": ""
        },
        "pbs": {
          "namespace": "user",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "pbs-comm": {
          "namespace": "user",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-spire-postgres": {
          "namespace": "spire",
          "type": "StatefulSet"
          "status": ""
          "balanced": ""
        },
        "spire-postgres": {
          "namespace": "spire",
          "type": "StatefulSet"
          "status": ""
          "balanced": ""
        },
        "cray-spire-server": {
          "namespace": "spire",
          "type": "StatefulSet"
          "status": ""
          "balanced": ""
        },
        "spire-server": {
          "namespace": "spire",
          "type": "StatefulSet"
          "status": ""
          "balanced": ""
        },
        "cilium-operator": {
          "namespace": "kube-system",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-smd": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-smd-postgres": {
          "namespace": "services",
          "type": "StatefulSet"
          "status": ""
          "balanced": ""
        },
        "cray-bss": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-bss-bitnami-etcd": {
          "namespace": "services",
          "type": "StatefulSet"
          "status": ""
          "balanced": ""
        },
        "cray-tftp": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-ipxe-aarch64": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-ipxe-x86-64": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-vault-configurer": {
          "namespace": "vault",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-vault-operator": {
          "namespace": "vault",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-vault": {
          "namespace": "vault",
          "type": "StatefulSet"
          "status": ""
          "balanced": ""
        },
        "cray-sts": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cfs-ara": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cfs-hwsync-agent": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cfs-trust": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-cfs-api": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-cfs-api-db": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-cfs-batcher": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-cfs-operator": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-bos": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-bos-db": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "nexus": {
          "namespace": "nexus",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "kyverno-admission-controller": {
          "namespace": "kyverno",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "kyverno-background-controller": {
          "namespace": "kyverno",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "kyverno-cleanup-controller": {
          "namespace": "kyverno",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "kyverno-reports-controller": {
          "namespace": "kyverno",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-certmanager-cert-manager": {
          "namespace": "cert-manager",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-certmanager-cert-manager-cainjector": {
          "namespace": "cert-manager",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-certmanager-cert-manager-webhook": {
          "namespace": "cert-manager",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "istio-operator": {
          "namespace": "istio-operator",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "istio-ingressgateway": {
          "namespace": "istio-system",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "istio-ingressgateway-customer-admin": {
          "namespace": "istio-system",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "istio-ingressgateway-customer-user": {
          "namespace": "istio-system",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "istio-ingressgateway-hmn": {
          "namespace": "istio-system",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "istiod": {
          "namespace": "istio-system",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "kiali": {
          "namespace": "istio-system",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "gitea-vcs": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "gitea-vcs-postgres": {
          "namespace": "services",
          "type": "StatefulSet"
          "status": ""
          "balanced": ""
        },
        "cray-bss": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-bss-bitnami-etcd": {
          "namespace": "services",
          "type": "StatefulSet"
          "status": ""
          "balanced": ""
        },
        "cray-sls": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-sls-postgres": {
          "namespace": "services",
          "type": "StatefulSet"
          "status": ""
          "balanced": ""
        },
        "cray-power-control": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-power-control-bitnami-etcd": {
          "namespace": "services",
          "type": "StatefulSet"
          "status": ""
          "balanced": ""
        },
        "cray-capmc": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "cray-tftp": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "gitea-vcs": {
          "namespace": "services",
          "type": "Deployment"
          "status": ""
          "balanced": ""
        },
        "gitea-vcs-postgres": {
          "namespace": "services",
          "type": "StatefulSet"
          "status": ""
          "balanced": ""
        },
        "kube-apiserver": {
          "namespace": "kube-system",
          "type": "pod"
          "status": ""
        },
        "kube-controller-manager": {
          "namespace": "kube-system",
          "type": "pod"
          "status": ""
        },
        "kube-scheduler": {
          "namespace": "kube-system",
          "type": "pod"
          "status": ""
        }
      }
    }
